name: Publish release

on:
  pull_request:
    types:
      - closed
    branches:
      - main

permissions:
  contents: write
  id-token: write

jobs:
  create-tag:
    name: Create tag
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true && contains(github.event.pull_request.labels.*.name, 'new-release')
    outputs:
      tag-name: ${{ steps.prepare-tag.outputs.tag-name }}
    steps:
      - name: Parse tag
        id: prepare-tag
        run: |
          branch_name="${{ github.event.pull_request.head.ref }}"
          tag_name=$(echo $branch_name | sed 's/version\///')
          echo "tag-name=$tag_name" >> $GITHUB_OUTPUT

      - name: Checkout branch
        uses: actions/checkout@v4.1.1

      - name: Create tag
        run: |
          git tag "${{ steps.prepare-tag.outputs.tag-name }}"

      - name: Push tag to origin
        run: git push origin "${{ steps.prepare-tag.outputs.tag-name }}"
